name: Run all tests

on: [push]

jobs:
  
  build:
    # Job name is Greeting
    name: test with ${{ matrix.ij_product }}
    # This job runs on Linux
    runs-on: ubuntu-18.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ij_product: ['intellij-2020.1']
        experimental: [false]
#        include:
#          - ij_product: 'intellij-2020.2'
#            experimental: true
    container:
      image: l.gcr.io/google/bazel:3.5.0
    steps:
      - name: install bazelisk
        run: |
            curl -L --output /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
            chmod +x /usr/local/bin/bazel
            which bazel
      - uses: actions/checkout@v2

      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: /github/home/.bazel_cache_folders
          key: ${{ github.ref }}
          restore-keys: |
            ${{ github.ref }}
            refs/heads/master
      - name: run bazel
        continue-on-error: ${{ matrix.experimental }}
        run: |
            mkdir -p /github/home/.bazel_caches/http
            mkdir -p /github/home/.bazel_caches/disk
            bazel --bazelrc=.bazelrc.remote test --repository_cache=/github/home/.bazel_caches/http --disk_cache=/github/home/.bazel_caches/disk -k --define=ij_product=${{ matrix.ij_product }} --test_output=errors //:ijwb_tests 